spring:
  profiles:
    active: dev, security, email
  config:
    import:
      - application-email.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  web:
    resources:
      add-mappings: false