spring:
  config:
    activate:
      on-profile: email
  mail:

    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?