spring:
  config:
    activate:
      on-profile: security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ""
            redirect-uri: http://api.daengplace.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
            provider: kakao
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://api.daengplace.com/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
            client-name: Google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: ${JWT_SECRET_KEY}
    refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
    access-token-validity: 600000
    refresh-token-validity: 2592000000

dog:
  api:
    key: ${DOG_API_KEY}