spring:
  profiles:
    active: dev,security,email

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    com.mycom: DEBUG

file:
  upload-dir: src/main/resources/static/img